// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteDeployment struct {
	Name string `json:"name"`
}

type Message struct {
	Text string `json:"text"`
}

type NewDeployment struct {
	Name  string `json:"name"`
	Image string `json:"image"`
}

type NewService struct {
	Name string `json:"name"`
}

type UpdateDeployment struct {
	Name  string `json:"name"`
	Image string `json:"image"`
}
